### PR TITLE
duplicated migration causes tests to fail

### PR DESCRIPTION
**Pull request by jlsjonas**
image

Already existing [here](https://github.com/laravel-enso/Enso/blob/master/database/migrations/2017_01_01_111000_create_users_table.php), any modifications (which make sense when customizing the framework) end up in a race condition between which of the 2 files gets read first. If Core is supposed to be pluggable in the future it shouldn't have a user create table as this would likely conflict with an existing structure.

### CODE REVIEW

**Comment by aocneanu** [comment]
The solution is removing the migration from Enso.

**Comment by jlsjonas** [comment]
It's not, please see the second statement.

Also I thought I could fix it with an update table; but you have to either make it nullable or add a default value (neither of which is realistic for production.

**Comment by aocneanu** [comment]
>It's not, please see the second statement.

It surely is. It needs to exist in the core package and have the proper structure.

When Core will be pluggable devs won't have the current enso migration in their projects, but their own, so we will need another aproach anyway.

>Also I thought I could fix it with an update table; but you have to either make it nullable or add a default value (neither of which is realistic for production.

You can fix anything with an update migration.

**Comment by jlsjonas** [comment]
>You can fix anything with an update migration.

you can workaround, but I was forced to set a default value (even though; at moment of migration; there shouldn't be any records yet as it happens right after the creation migrate) which doesn't make sense for a username field (in this case; there will likely be others added later on).

But I guess I'll close this issue as there is a viable workaround & the strategy for pluggability will need more drastic changes anyway

**Pull request closed without merging**
