### PR TITLE
Fully configurable Pusher/Echo (laravel-websockets support)

### PR DESCRIPTION
**Pull request by jlsjonas**
Required for https://github.com/laravel-enso/Enso/pull/190

Closes https://github.com/laravel-enso/Notifications/issues/5

### CODE REVIEW

**Comment by jlsjonas** [comment]
Testing out configurations as setting `wsHost` & `httpHost` to null actually uses null as host instead of defaults apparently (avoiding regression) will update asap

**Comment by jlsjonas** [comment]
Conditionally including the host & port configs (see [spec](https://github.com/tc39/proposal-object-rest-spread/issues/45) for syntax used)

tested & working with defaults (pusher.com) while still allowing alternative servers/hosts

**Comment by aocneanu** [comment]
It took me some time to understand exactly the flow that you are proposing in here & laravel-enso/enso#190 but I guess I finally did.

Will add some small changes soon.

**Comment by aocneanu** [comment]
I will have to revert this because everything is broken in dev / prod

https://pusher.com/docs/clusters

**Comment by jlsjonas** [comment]
Interesting, I'll check on Monday what might be causing your issues with it (and ideally PR a fix that takes it into account).
At first glance it might be that pusher's app cluster isn't auto-generated because of the presence of the host field (it didn't ignore `undefined`), might be worth trying to build the URL php-side as host, to see if it fixes the issue.
Although this sounds as it's being caused by an underlying upstream issue.

**Comment by aocneanu** [comment]
Wait a few days until I will have the core  UI migrated to npm and commit then on the new repo.

**Comment by jlsjonas** [comment]
Debugged the issue (still using pusher locally, except while implementing this 😅 ), as I figured the issue is that empty or undefined keys are not ignored.
Along with the fact that their own documented `scheme` parameter seems defunct (at least for BE)

Did find a reasonably clean fix:

```php
'options' => array_filter([
                'host' => env('PUSHER_APP_HOST'),
                'port' => env('PUSHER_APP_PORT'),
                'cluster' => env('PUSHER_APP_CLUSTER'),
            ]),
```
(wrapping the options array for the `pusher` config (`config/broadcasting.php`) in an `array_filter` to remove _empty_ keys & removing the scheme operator as the default value seems good enough)

**Pull request merged**
